/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"


void
printer_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	account  query_balance_1_arg;
	int  *result_2;
	account  update_balance_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PRINTER, PRINTER_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	account* acc;
	acc = (account*)malloc(sizeof(account));
	acc->accno = 123;
	acc->update = 0;
	acc->money = -1;		
	result_1 = query_balance_1(acc, clnt);
	printf("%d\n", *result_1);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
//	result_2 = update_balance_1(&update_balance_1_arg, clnt);
//	if (result_2 == (int *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printer_1 (host);
exit (0);
}
