/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank.h"

bool_t
xdr_account (XDR *xdrs, account *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->accno))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->update))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->money))
		 return FALSE;
	return TRUE;
}
