/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct account {
	int accno;
	bool_t update;
	int money;
};
typedef struct account account;

#define PRINTER 0x2fffffff
#define PRINTER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUERY_BALANCE 1
extern  int * query_balance_1(account *, CLIENT *);
extern  int * query_balance_1_svc(account *, struct svc_req *);
#define UPDATE_BALANCE 2
extern  int * update_balance_1(account *, CLIENT *);
extern  int * update_balance_1_svc(account *, struct svc_req *);
extern int printer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUERY_BALANCE 1
extern  int * query_balance_1();
extern  int * query_balance_1_svc();
#define UPDATE_BALANCE 2
extern  int * update_balance_1();
extern  int * update_balance_1_svc();
extern int printer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_account (XDR *, account*);

#else /* K&R C */
extern bool_t xdr_account ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK_H_RPCGEN */
