/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ATM_H_RPCGEN
#define _ATM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct transaction {
	int account_no;
	int amount;
};
typedef struct transaction transaction;

#define ATM 0x2fffffff
#define ATM_v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define deposit 1
extern  void * deposit_1(transaction *, CLIENT *);
extern  void * deposit_1_svc(transaction *, struct svc_req *);
#define withdraw 2
extern  void * withdraw_1(transaction *, CLIENT *);
extern  void * withdraw_1_svc(transaction *, struct svc_req *);
#define balance 3
extern  int * balance_1(int *, CLIENT *);
extern  int * balance_1_svc(int *, struct svc_req *);
extern int atm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define deposit 1
extern  void * deposit_1();
extern  void * deposit_1_svc();
#define withdraw 2
extern  void * withdraw_1();
extern  void * withdraw_1_svc();
#define balance 3
extern  int * balance_1();
extern  int * balance_1_svc();
extern int atm_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_transaction (XDR *, transaction*);

#else /* K&R C */
extern bool_t xdr_transaction ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ATM_H_RPCGEN */
