/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "atm.h"

bool_t
xdr_transaction (XDR *xdrs, transaction *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->account_no))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	return TRUE;
}
